<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/src/Auth.php';require_once dirname(__DIR__,2).'/src/ClientIp.php';require_once dirname(__DIR__,2).'/src/Database.php';require_once dirname(__DIR__,2).'/src/JsonResponse.php';require_once dirname(__DIR__,2).'/src/RepresentationRequestRepository.php';require_once dirname(__DIR__,2).'/src/RepresentationRequestContactService.php';require_once dirname(__DIR__,2).'/src/MailSettingsRepository.php';require_once dirname(__DIR__,2).'/src/MailService.php';
require_once dirname(__DIR__,2).'/src/RepresentationAssignmentService.php';
if($_SERVER['REQUEST_METHOD']!=='POST')JsonResponse::send(['error'=>'Nur POST ist erlaubt.'],405);Auth::requireCsrfJson();$identity=Auth::user();
try{$payload=json_decode(file_get_contents('php://input')?:'',true,8,JSON_THROW_ON_ERROR);$db=(new Database())->connection();$settings=new MailSettingsRepository($db);$mailer=new MailService($settings);$service=new RepresentationRequestContactService($db,new RepresentationRequestRepository($db),$settings,$mailer,new RepresentationAssignmentService($db,$settings,$mailer));$action=(string)($payload['action']??'send');$requestId=(int)($payload['request_id']??0);$message=(string)($payload['custom_message']??'');
if(is_array($identity)&&($identity['role']??null)==='user'){if($action==='preview')JsonResponse::send(['preview'=>$service->preview((int)$identity['user_id'],$requestId,$message)]);$service->send((int)$identity['user_id'],$requestId,$message);}
else{$first=(string)($payload['contact_first_name']??'');$last=(string)($payload['contact_last_name']??'');$email=(string)($payload['contact_email']??'');if($action==='preview')JsonResponse::send(['preview'=>$service->previewAnonymous($requestId,$first,$last,$email,$message)]);$service->sendAnonymous($requestId,$first,$last,$email,$message,ClientIp::address());}
JsonResponse::send(['message'=>'Deine Rückmeldung wurde gesendet.']);}
catch(JsonException|InvalidArgumentException|DomainException $e){JsonResponse::send(['error'=>$e->getMessage()],400);}catch(Throwable){JsonResponse::send(['error'=>'Die Rückmeldung konnte nicht gesendet werden.'],500);}
