<?php

declare(strict_types=1);

$root=is_file(__DIR__.'/../app/src/Database.php')?__DIR__.'/../app':'/var/www/html';
foreach(['Database','HttpException','HttpClient','BniRequestPolicy','BniGlobalThrottle','BniRequestEventRepository','BniClient','BniMemberListClient','BniMemberDirectoryConfigResolver']as$file)require_once$root.'/src/'.$file.'.php';
$check=static function(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);};
$db=(new Database(':memory:'))->connection();$events=new BniRequestEventRepository($db);$now=1_800_000_000_000;$clock=$now;$throttle=new BniGlobalThrottle($db,static function()use(&$clock):int{return$clock;},static function(int$ms)use(&$clock):void{$clock+=$ms;});
$calls=0;$transport=static function()use(&$calls):array{$calls++;return match($calls){1=>['status'=>200,'headers'=>[],'body'=>json_encode(['content'=>['orgId'=>1,'chapterDetails'=>['name'=>'Test']]],JSON_THROW_ON_ERROR)],2=>['status'=>429,'headers'=>[],'body'=>'{}'],3=>['status'=>403,'headers'=>[],'body'=>'{}'],default=>throw new RuntimeException('mock network failure')};};
$client=new BniClient(new HttpClient($transport),$throttle,$events,true);
$client->getChapterDetails('one',null,'manual');foreach([429,403]as$expected){try{$client->getChapterDetails('next',null,'automatic');$check(false,"HTTP $expected wurde nicht geworfen.");}catch(HttpException$e){$check($e->statusCode===$expected,"HTTP $expected falsch erfasst.");}}try{$client->getChapterDetails('network',null,'usage_detail');$check(false,'Netzwerkfehler wurde nicht geworfen.');}catch(RuntimeException){}
$rows=$db->query('SELECT request_type,trigger_type,http_status,result_type FROM bni_request_events ORDER BY id')->fetchAll();$check(count($rows)===4&&array_column($rows,'result_type')===['success','rate_limited','forbidden','network_error'],'Gestartete Success-/429-/403-/Netzwerkrequests werden nicht exakt erfasst.');$check(array_column($rows,'trigger_type')===['manual','automatic','automatic','usage_detail'],'Triggertypen fehlen in Requestevents.');
$before=(int)$db->query('SELECT COUNT(*) FROM bni_request_events')->fetchColumn();$throttle->reserveStartSlot();$check((int)$db->query('SELECT COUNT(*) FROM bni_request_events')->fetchColumn()===$before,'Bloße Throttle-Reservierung erzeugt ein Event.');try{$client->getChapterDetails('cancelled',static function():void{throw new BniRequestNotStartedException('cancelled');},'usage_search');}catch(BniRequestNotStartedException){}$check((int)$db->query('SELECT COUNT(*) FROM bni_request_events')->fetchColumn()===$before,'Vor HTTP-Start abgebrochene Vorbereitung erzeugt ein Event.');
$created=gmdate('Y-m-d\TH:i:s\Z');$db->prepare("INSERT INTO organizations(org_id,org_type,chapter_name,chapter_url,cms_security_hash,created_at,updated_at)VALUES(70001,'CHAPTER','Monitor List','https://bni-test.de/de/chapter','hash',:now,:now),(70002,'CHAPTER','Monitor Discovery','https://bni-test.de/de/chapter','hash2',:now,:now)")->execute([':now'=>$created]);$db->prepare("INSERT INTO bni_member_directory_configs(org_id,endpoint,parameters,languages,website_type,website_id,mapped_widget_settings,referer,updated_at)VALUES(70001,'https://bni-test.de/memberlist','x=1','{}','3','1','[]','https://bni-test.de/de/chapter',:now)")->execute([':now'=>$created]);
$guard=getenv('CROSSCHAPP_DISABLE_EXTERNAL_HTTP');putenv('CROSSCHAPP_DISABLE_EXTERNAL_HTTP=0');try{(new BniMemberListClient($db,static fn():array=>['status'=>200,'body'=>'<div id="members"></div>','headers'=>[]],null,$throttle,true,$events))->fetch(70001);$resolverHtml='<input id="website_type" value="3"><input id="website_id" value="1"><script>var mappedWidgetSettings = \'[]\';</script>';(new BniMemberDirectoryConfigResolver($db,static fn():array=>['status'=>200,'body'=>$resolverHtml,'headers'=>[]],null,$throttle,true,$events))->resolve(70002);}finally{putenv($guard===false?'CROSSCHAPP_DISABLE_EXTERNAL_HTTP':"CROSSCHAPP_DISABLE_EXTERNAL_HTTP=$guard");}
$types=$db->query('SELECT request_type FROM bni_request_events ORDER BY id DESC LIMIT 2')->fetchAll(PDO::FETCH_COLUMN);$check($types===['member_discovery','member_list'],'Memberlist und Discovery werden nicht zentral erfasst.');

$db->exec('DELETE FROM bni_request_events');$now=(int)(strtotime('2026-08-27T12:00:30Z')*1000);$insert=$db->prepare("INSERT INTO bni_request_events(started_at_ms,request_type,result_type)VALUES(:ms,'chapter_detail','success')");$add=static function(int$minuteOffset,int$count)use($insert,$now):void{for($i=0;$i<$count;$i++)$insert->execute([':ms'=>$now+$minuteOffset*60000-$i]);};foreach([[-45,6],[-20,5],[-7,4],[-4,1],[-2,2],[0,3]]as[$offset,$count])$add($offset,$count);$add(-5*1440,7);$add(-10*1440,7);$add(-31*1440,9);$add(-36*1440,11);
foreach([1=>3,5=>6,10=>10,30=>15,60=>21]as$window=>$expected){$result=$events->performance($window,$now);$check(count($result['last_24h'])===1440&&$result['last_24h'][array_key_last($result['last_24h'])]['count']===$expected,"Rollierendes Fenster $window Minuten ist falsch.");$check($result['requests_24h']===21&&$result['requests_60m']===21,'24h-/60m-Kennzahlen sind falsch.');$check($result['peak_30d']['count']===7&&$result['peak_30d']['minute']===gmdate('Y-m-d\TH:i:00\Z',intdiv($now-5*86400000,60000)*60),'30-Tage-Peak oder neuester Gleichstand ist falsch.');}
$removed=$events->cleanup(35,$now);$remainingOld=$db->prepare('SELECT COUNT(*) FROM bni_request_events WHERE started_at_ms<:cutoff');$remainingOld->execute([':cutoff'=>$now-35*86400000]);$check($removed===11&&(int)$remainingOld->fetchColumn()===0,'35-Tage-Retention entfernt Events nicht korrekt.');
$db->exec('DELETE FROM bni_request_events');$measured=$db->prepare("INSERT INTO bni_request_events(started_at_ms,request_type,result_type,throttle_reserved_at_ms,throttle_wait_ms)VALUES(:started,'chapter_detail','success',:reserved,:wait)");foreach([0,5,20,100,200]as$index=>$wait)$measured->execute([':started'=>$now-$index*60000,':reserved'=>$now-$index*60000-$wait,':wait'=>$wait]);$insert->execute([':ms'=>$now-300000]);$db->exec('UPDATE bni_request_throttle SET last_reserved_start_ms='.($now+1600).' WHERE id=1');$throttleStats=$events->performance(5,$now)['throttle'];$check($throttleStats['minimum_interval_ms']===1500&&$throttleStats['requests_24h']===6&&$throttleStats['measured_requests_24h']===5,'Mindestabstand, Gesamtmenge oder historische NULL-Events sind falsch.');$check($throttleStats['waited_requests_24h']===3&&$throttleStats['immediate_requests_24h']===2,'Wartende und unmittelbare Requests werden falsch klassifiziert.');$check($throttleStats['avg_wait_ms_24h']===65&&$throttleStats['max_wait_ms_24h']===200&&$throttleStats['p95_wait_ms_24h']===200,'Durchschnitt, Maximum oder p95 der Wartezeit sind falsch.');$check($throttleStats['last_actual_start_ms']===$now&&$throttleStats['last_reserved_start_ms']===$now+1600,'Letzter tatsächlicher Start oder reservierter Slot ist falsch.');$check(count($throttleStats['series_24h'])===289&&array_filter($throttleStats['series_24h'],static fn(array$point):bool=>$point['maximum_wait_ms']!==null)!==[],'5-Minuten-Wartezeitserie fehlt.');
echo"PASS BNI-Leistungsmonitor: echte Starts, Ergebnisse, Rollfenster, Peak, Wartezeiten und Retention\n";
