#!/usr/bin/env python3
import json,time,urllib.request
BASE='http://127.0.0.1:9516'
def request(method,path,payload=None):
    req=urllib.request.Request(BASE+path,data=None if payload is None else json.dumps(payload).encode(),method=method,headers={'Content-Type':'application/json'})
    with urllib.request.urlopen(req) as response:return json.loads(response.read())['value']
session=request('POST','/session',{'capabilities':{'alwaysMatch':{'browserName':'chrome','goog:chromeOptions':{'args':['--headless','--no-sandbox','--disable-gpu','--window-size=1440,1000']},'goog:loggingPrefs':{'browser':'ALL','performance':'ALL'}}}})['sessionId']
def script(source):return request('POST',f'/session/{session}/execute/sync',{'script':source,'args':[]})
def async_script(source):return request('POST',f'/session/{session}/execute/async',{'script':source,'args':[]})
try:
    request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=login'});time.sleep(.3)
    script("const f=document.querySelector('#login-form');f.login.value='admin';f.password.value='admin';f.requestSubmit();");time.sleep(.8)
    initial_network=request('POST',f'/session/{session}/log',{'type':'performance'})
    script("const panel=document.querySelector('#invitations-panel');panel.open=true;panel.dispatchEvent(new Event('toggle'));");time.sleep(.8)
    admin_initial=script("const root=document.querySelector('#invitation-chapter-results').closest('[data-chapter-picker]'),list=root.querySelector('.chapter-picker-list'),guidance=root.querySelector('[data-chapter-picker-guidance]'),style=getComputedStyle(list);return {items:list.children.length,hidden:list.hidden,guidance:!guidance.hidden,clientHeight:list.clientHeight,scrollHeight:list.scrollHeight,overflowY:style.overflowY,structure:[...root.children].map(x=>x.tagName+'.'+x.className)};")
    assert admin_initial['items']>20 and not admin_initial['hidden'] and not admin_initial['guidance'] and 300<=admin_initial['clientHeight']<=380 and admin_initial['scrollHeight']>admin_initial['clientHeight'] and admin_initial['overflowY'] in ['auto','scroll'],admin_initial
    before=script("return [...document.querySelectorAll('#invitation-chapter-results .chapter-picker-item')].slice(0,10).map(row=>({text:row.innerText,html:row.innerHTML,value:row.querySelector('input')?.value,strong:row.querySelector('strong')?.textContent,small:row.querySelector('small')?.textContent}));")
    admin_geometry=script("const container=document.querySelector('#invitation-chapter-results'),rows=[...container.querySelectorAll('.chapter-picker-item')].slice(0,10),pick=node=>{const s=getComputedStyle(node),r=node.getBoundingClientRect();return {display:s.display,width:s.width,gap:s.gap,margin:s.margin,padding:s.padding,borderBottom:s.borderBottom,whiteSpace:s.whiteSpace,alignItems:s.alignItems,fontFamily:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,top:r.top,bottom:r.bottom,height:r.height,left:r.left,right:r.right}};return {container:pick(container),rows:rows.map(row=>({...pick(row),radio:pick(row.querySelector('input')),strong:pick(row.querySelector('strong')),small:pick(row.querySelector('small'))})),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth};")
    chapters=async_script("const done=arguments[arguments.length-1];fetch('/api/auth/chapters.php').then(async r=>done({status:r.status,data:await r.json()}));")
    king=next((item for item in chapters['data']['chapters'] if 'Königsforst' in str(item.get('chapterName',''))),None)
    assets=async_script("const done=arguments[arguments.length-1],scripts=[...document.scripts].map(x=>x.src),app=scripts.find(x=>x.includes('/assets/app.js'))||'',picker=scripts.find(x=>x.includes('/assets/chapter-picker.js'))||'';Promise.all([fetch(app,{cache:'no-store'}).then(r=>r.text()),fetch(picker,{cache:'no-store'}).then(r=>r.text())]).then(([appText,pickerText])=>done({app,picker,componentLoaded:typeof window.CrossChappChapterPicker?.create==='function',oldInvitationRenderer:appText.includes('renderInvitationChapters'),hasFallback:pickerText.includes(\"chapterName || 'Chapter'\")||pickerText.includes(\"chapterName ?? 'Chapter'\"),hasFilter:pickerText.includes(\"typeof item.chapterName === 'string'\"),hasPostal:pickerText.includes('item.postalCode, item.city, item.region')}));")
    network=initial_network+request('POST',f'/session/{session}/log',{'type':'performance'});messages=[json.loads(entry['message'])['message'] for entry in network];panel_urls=[item['params']['request']['url'] for item in messages if item['method']=='Network.requestWillBeSent' and ('/api/auth/chapters.php' in item['params']['request']['url'] or '/api/admin/invitations.php' in item['params']['request']['url'])]
    cologne=script("const input=document.querySelector('#invitation-search');input.value='Köln';input.dispatchEvent(new Event('input',{bubbles:true}));return [...document.querySelectorAll('#invitation-chapter-results .chapter-picker-item')].slice(0,10).map(row=>({strong:row.querySelector('strong')?.textContent,small:row.querySelector('small')?.textContent,text:row.innerText}));")
    search=script("const input=document.querySelector('#invitation-search');input.value='Königsforst';input.dispatchEvent(new Event('input',{bubbles:true}));const row=document.querySelector('#invitation-chapter-results .chapter-picker-item'),result=row?{text:row.innerText,html:row.innerHTML,value:row.querySelector('input').value,strong:row.querySelector('strong').textContent,small:row.querySelector('small').textContent}:null;row?.querySelector('input').click();return result?{...result,selected:document.querySelector('#invitation-selected-chapter').textContent,checked:row.querySelector('input').checked,listVisible:!document.querySelector('#invitation-chapter-results').hidden}:null;")
    assert chapters['status']==200 and king=={'orgId':44628,'chapterName':'Königsforst BNI (Overath)','city':'Rösrath-Forsbach','postalCode':'51503','region':'Bergisches Land','countryCode':'DE'},king
    assert len(before)==10 and all(row['strong']!='Chapter' and row['strong'].strip() for row in before) and any(row['strong']!='Chapter' for row in before),before
    assert len(admin_geometry['rows'])==10 and admin_geometry['container']['display']=='grid' and all(row['display']=='grid' and row['height']>0 for row in admin_geometry['rows']) and all(admin_geometry['rows'][i]['top']>=admin_geometry['rows'][i-1]['bottom']-.5 for i in range(1,10)) and all(row['small']['top']>=row['strong']['bottom']-.5 for row in admin_geometry['rows']) and not admin_geometry['overflow'],admin_geometry
    assert len(cologne)>=1 and all(row['strong'] and row['strong']!='Chapter' and 'Köln' in row['text'] for row in cologne),cologne
    assert all(item.get('chapterName') and str(item['chapterName']).strip() for item in chapters['data']['chapters']) and all(set(['orgId','chapterName','city','postalCode','region','countryCode']).issubset(item) for item in chapters['data']['chapters'][:10]),chapters['data']['chapters'][:10]
    assert search and 'Königsforst BNI (Overath)' in search['text'] and '51503' in search['text'] and 'Rösrath-Forsbach' in search['text'] and 'Bergisches Land' in search['text'] and 'Deutschland' in search['text'] and search['strong']!='Chapter' and search['value']=='44628' and search['selected']=='Ausgewähltes Chapter: Königsforst BNI (Overath)' and search['checked'] and search['listVisible'],search
    selection_change=script("const input=document.querySelector('#invitation-search');input.value='4-Tore';input.dispatchEvent(new Event('input',{bubbles:true}));const radio=document.querySelector('#invitation-chapter-results .chapter-picker-item input');radio.click();return {org:document.querySelector('#invitation-form').elements.home_chapter_org_id.value,selected:document.querySelector('#invitation-selected-chapter').textContent,visible:!document.querySelector('#invitation-chapter-results').hidden};")
    assert selection_change['org']=='21067' and '4-Tore' in selection_change['selected'] and selection_change['visible'],selection_change
    assert '?v=' in assets['app'] and '?v=' in assets['picker'] and assets['componentLoaded'] and assets['hasPostal'] and assets['hasFilter'] and not assets['hasFallback'] and not assets['oldInvitationRenderer'],assets
    assert any('/api/auth/chapters.php' in url for url in panel_urls) and any('/api/admin/invitations.php' in url for url in panel_urls),panel_urls
    reset=script("document.querySelector('#clear-invitation-chapter').click();const list=document.querySelector('#invitation-chapter-results');return {items:list.children.length,visible:!list.hidden,selected:document.querySelector('#invitation-selected-chapter').textContent,org:document.querySelector('#invitation-form').elements.home_chapter_org_id.value};")
    assert reset['items']==admin_initial['items'] and reset['visible'] and reset['selected']=='Kein Chapter ausgewählt.' and reset['org']=='',reset
    invitation_success=async_script("const done=arguments[arguments.length-1],originalFetch=window.fetch,form=document.querySelector('#invitation-form'),search=document.querySelector('#invitation-search');search.value='Königsforst';search.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#invitation-chapter-results .chapter-picker-item input').click();form.elements.first_name.value='Browser';form.elements.last_name.value='Test';form.elements.email.value='browser-invitation@example.test';window.fetch=(input,options={})=>String(input).endsWith('/api/admin/invitations.php')&&options.method==='POST'?new Promise(resolve=>setTimeout(()=>resolve(new Response(JSON.stringify({ok:true}),{status:200,headers:{'Content-Type':'application/json'}})),25)):originalFetch(input,options);form.requestSubmit();setTimeout(()=>{window.fetch=originalFetch;done({firstName:form.elements.first_name.value,lastName:form.elements.last_name.value,email:form.elements.email.value,org:form.elements.home_chapter_org_id.value,selected:document.querySelector('#invitation-selected-chapter').textContent,search:search.value,listVisible:!document.querySelector('#invitation-chapter-results').hidden,message:document.querySelector('#invitation-message').textContent,messageClass:document.querySelector('#invitation-message').className});},250);")
    assert invitation_success=={'firstName':'','lastName':'','email':'','org':'','selected':'Kein Chapter ausgewählt.','search':'','listVisible':True,'message':'Einladung wurde versendet.','messageClass':'message success'},invitation_success
    request('POST',f'/session/{session}/window/rect',{'width':390,'height':844});time.sleep(.2);mobile_geometry=script("const container=document.querySelector('#invitation-chapter-results'),rows=[...container.querySelectorAll('.chapter-picker-item')].slice(0,10).map(x=>x.getBoundingClientRect()),box=container.getBoundingClientRect();return {count:rows.length,vertical:rows.every((r,i)=>i===0||r.top>=rows[i-1].bottom-.5),heights:rows.map(x=>x.height),overflow:container.scrollWidth>container.clientWidth,rowOverflow:rows.some(r=>r.left<box.left-.5||r.right>box.right+.5)};");assert mobile_geometry['count']==10 and mobile_geometry['vertical'] and all(x>0 for x in mobile_geometry['heights']) and not mobile_geometry['overflow'] and not mobile_geometry['rowOverflow'],mobile_geometry
    request('POST',f'/session/{session}/window/rect',{'width':1440,'height':1000});script("document.querySelector('#logout-button').click()");time.sleep(.4);request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=register'});time.sleep(.8)
    registration_initial=script("const root=document.querySelector('#home-chapter-results').closest('[data-chapter-picker]'),list=root.querySelector('.chapter-picker-list'),guidance=root.querySelector('[data-chapter-picker-guidance]');return {items:list.children.length,hidden:list.hidden,guidance:!guidance.hidden,structure:[...root.children].map(x=>x.tagName+'.'+x.className)};")
    assert registration_initial['items']==0 and registration_initial['hidden'] and registration_initial['guidance'] and registration_initial['structure']==admin_initial['structure'],(registration_initial,admin_initial)
    script("const country=document.querySelector('#home-chapter-country');country.value='DE';country.dispatchEvent(new Event('input',{bubbles:true}));")
    registration_geometry=script("const container=document.querySelector('#home-chapter-results'),rows=[...container.querySelectorAll('.chapter-picker-item')].slice(0,10),pick=node=>{const s=getComputedStyle(node),r=node.getBoundingClientRect();return {display:s.display,width:s.width,gap:s.gap,margin:s.margin,padding:s.padding,borderBottom:s.borderBottom,whiteSpace:s.whiteSpace,alignItems:s.alignItems,fontFamily:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,top:r.top,bottom:r.bottom,height:r.height}};return {container:pick(container),rows:rows.map(row=>({...pick(row),radio:pick(row.querySelector('input')),strong:pick(row.querySelector('strong')),small:pick(row.querySelector('small'))}))};")
    assert len(registration_geometry['rows'])==10 and registration_geometry['container']['display']==admin_geometry['container']['display'] and all(row['display']=='grid' for row in registration_geometry['rows']) and all(registration_geometry['rows'][i]['top']>=registration_geometry['rows'][i-1]['bottom']-.5 for i in range(1,10)),registration_geometry
    for admin_row,registration_row in zip(admin_geometry['rows'],registration_geometry['rows']):
        assert admin_row['height']==registration_row['height'] and admin_row['padding']==registration_row['padding'] and admin_row['borderBottom']==registration_row['borderBottom'] and admin_row['strong']['fontFamily']==registration_row['strong']['fontFamily'] and admin_row['strong']['fontSize']==registration_row['strong']['fontSize'] and admin_row['small']['fontSize']==registration_row['small']['fontSize'] and admin_row['radio']['height']==registration_row['radio']['height'],(admin_row,registration_row)
    logs=request('POST',f'/session/{session}/log',{'type':'browser'});assert not [entry for entry in logs if entry.get('level')=='SEVERE'],logs
    print(json.dumps({'adminInitial':admin_initial,'registrationInitial':registration_initial,'firstTen':before,'apiFirstTen':chapters['data']['chapters'][:10],'panelRequests':panel_urls,'koeln':cologne,'koenigsforst':king,'asset':assets,'searchAfter':search,'selectionChange':selection_change,'reset':reset,'invitationSuccess':invitation_success,'adminGeometry':admin_geometry,'mobileGeometry':mobile_geometry,'registrationGeometry':registration_geometry},ensure_ascii=False))
    print('PASS Chromium: Einladungsauswahl zeigt echte Chapternamen und vollständige Königsforst-Daten')
finally:request('DELETE',f'/session/{session}')
