<?php
declare(strict_types=1);
$app=is_file(__DIR__.'/../app/src/Database.php')?__DIR__.'/../app':'/var/www/html';
require_once $app.'/src/Database.php';require_once $app.'/src/UserRepository.php';require_once $app.'/src/MailSettingsRepository.php';require_once $app.'/src/MailService.php';require_once $app.'/src/RepresentationAssignmentService.php';
$path=sys_get_temp_dir().'/crosschapp-assignments-'.bin2hex(random_bytes(5)).'.sqlite';
try{$db=(new Database($path))->connection();$now=gmdate('Y-m-d\TH:i:s\Z');$db->exec("INSERT INTO organizations(org_id,org_type,chapter_name,chapter_url,meeting_day,meeting_time,timezone,created_at,updated_at)VALUES(7001,'CHAPTER','Chapter X','https://example.test/chapter-x','Donnerstag','07:00','Europe/Berlin','$now','$now'),(7002,'CHAPTER','Chapter Y',NULL,'Donnerstag','07:00','Europe/Berlin','$now','$now'),(7003,'CHAPTER','Chapter Z','javascript:alert(1)','Donnerstag','08:00','Europe/Berlin','$now','$now')");$users=new UserRepository($db);$requester=$users->create('Rita','Requester','rita@example.test',password_hash('password1',PASSWORD_DEFAULT),7001);$representative=$users->create('Vera','Vertreter','vera@example.test',password_hash('password2',PASSWORD_DEFAULT),7001);$competingRepresentative=$users->create('Zora','Zweite','zora@example.test',password_hash('password4',PASSWORD_DEFAULT),7002);$wrong=$users->create('Fritz','Falsch','fritz@example.test',password_hash('password3',PASSWORD_DEFAULT),7001);$db->exec("UPDATE users SET status='active',email_verified_at='$now'");
$insertRequest=$db->prepare('INSERT INTO representation_requests(user_id,org_id,request_date,created_at,updated_at)VALUES(?,?,?,?,?)');$requestIds=[];foreach([7001,7002,7003]as$orgId){$insertRequest->execute([$requester['id'],$orgId,'2099-09-10',$now,$now]);$requestIds[$orgId]=(int)$db->lastInsertId();}$requestId=$requestIds[7001];$db->exec("INSERT INTO representation_offers(user_id,org_id,all_dates,date_signature,created_at,updated_at)VALUES({$representative['id']},7001,1,'*','$now','$now')");$offerId=(int)$db->lastInsertId();
$settings=new MailSettingsRepository($db);$mails=[];$mailer=new MailService($settings,static function(...$args)use(&$mails){$mails[]=$args;});$service=new RepresentationAssignmentService($db,$settings,$mailer);
$requestContext=['id'=>$requestId,'request_date'=>'2099-09-10','recipient_id'=>$requester['id'],'contact_user_id'=>$representative['id']];$issued=$service->issueForRequest($requestContext,11);$competing=$service->issueForRequest(array_replace($requestContext,['contact_user_id'=>$competingRepresentative['id']]),12);assert(strlen($issued['token'])>=43);assert(!str_contains((string)$db->query('SELECT token_hash FROM representation_acceptance_tokens')->fetchColumn(),$issued['token']));$inspect=$service->inspect($issued['token']);assert($inspect['requiredUserId']===$requester['id']&&$inspect['direction']==='request_contact');
try{$service->accept($issued['token'],(int)$wrong['id']);assert(false);}catch(DomainException $e){assert(str_contains($e->getMessage(),'anderes Benutzerkonto'));}assert((int)$db->query('SELECT COUNT(*) FROM representation_assignments')->fetchColumn()===0);
$assignment=$service->accept($issued['token'],(int)$requester['id']);assert($assignment['status']==='active');assert((int)$db->query("SELECT COUNT(*) FROM representation_assignments WHERE status='active'")->fetchColumn()===1);assert(count($mails)===2);
try{$service->accept($issued['token'],(int)$requester['id']);assert(false);}catch(DomainException $e){assert(str_contains($e->getMessage(),'nicht mehr gültig'));}
try{$service->accept($competing['token'],(int)$requester['id']);assert(false);}catch(DomainException $e){assert(str_contains($e->getMessage(),'nicht mehr gültig')||str_contains($e->getMessage(),'vergeben'));}
foreach([7002,7003]as$orgId){$context=['id'=>$requestIds[$orgId],'request_date'=>'2099-09-10','recipient_id'=>$requester['id'],'contact_user_id'=>$representative['id']];$token=$service->issueForRequest($context,20+$orgId);$service->accept($token['token'],(int)$requester['id']);}
assert((int)$db->query("SELECT COUNT(*) FROM representation_assignments WHERE status='active' AND representative_user_id={$representative['id']} AND representation_date='2099-09-10'")->fetchColumn()===3);
$listed=$service->forUser((int)$requester['id']);assert(count($listed)===3&&$listed[0]['role']==='requester'&&$listed[0]['meetingTime']==='07:00'&&$listed[0]['counterpartIsBniMember']===true);assert(in_array('https://example.test/chapter-x',array_column($listed,'chapterUrl'),true)&&in_array(null,array_column($listed,'chapterUrl'),true));$service->cancel((int)$assignment['id'],(int)$representative['id']);assert((int)$db->query("SELECT COUNT(*) FROM representation_assignments WHERE status='active'")->fetchColumn()===2);assert((int)$db->query("SELECT COUNT(*) FROM representation_assignments WHERE status='cancelled'")->fetchColumn()===1);
$reopened=$service->issueForRequest(array_replace($requestContext,['contact_user_id'=>$competingRepresentative['id']]),30);$replacement=$service->accept($reopened['token'],(int)$requester['id']);assert($replacement['status']==='active'&&$replacement['representative_user_id']===$competingRepresentative['id']);
$service->cancel((int)$replacement['id'],(int)$requester['id']);$offerContext=['id'=>$offerId,'requester_id'=>$requester['id'],'recipient_id'=>$representative['id']];$offerToken=$service->issueForOffer($offerContext,'2099-09-10',31);$second=$service->accept($offerToken['token'],(int)$representative['id']);assert($second['status']==='active'&&$second['offer_id']===$offerId);
echo "PASS representation assignments: gleicher Vertreter in drei Chaptern am selben Tag erlaubt; nur konkreter Slot exklusiv und nach Storno wieder frei\n";
}finally{if(is_file($path))unlink($path);}
