<?php
declare(strict_types=1);
$app=is_file(__DIR__.'/../app/src/Database.php')?__DIR__.'/../app':'/var/www/html';foreach(['Database','UserRepository','MailSettingsRepository','MailService','RepresentationRequestRepository','RepresentationRequestContactService']as$class)require_once"$app/src/$class.php";
$check=static function(bool$c,string$m):void{if(!$c)throw new RuntimeException($m);};$pdo=(new Database(':memory:'))->connection();$now=gmdate('Y-m-d\TH:i:s\Z');$pdo->exec("INSERT INTO organizations(org_id,org_type,chapter_name,meeting_day,timezone,created_at,updated_at)VALUES(1,'CHAPTER','Gesuch Chapter','Freitag','Europe/Berlin','$now','$now'),(2,'CHAPTER','Kontakt Chapter','Montag','Europe/Berlin','$now','$now')");$users=new UserRepository($pdo);$owner=$users->create('Anna','Alpha','owner@example.test',password_hash('password1',PASSWORD_DEFAULT),1);$contact=$users->create('Bernd','Beta','contact@example.test',password_hash('password2',PASSWORD_DEFAULT),2);$pdo->exec("UPDATE users SET status='active',email_verified_at='$now'");
$date=(new DateTimeImmutable('next friday',new DateTimeZone('Europe/Berlin')))->format('Y-m-d');$requests=new RepresentationRequestRepository($pdo);$request=$requests->create((int)$owner['id'],$date);$mails=[];$settings=new MailSettingsRepository($pdo);$settings->saveCustomMessages('Angebotsspezifischer administrierter Starttext mit ausreichender Länge.','Gesuchsspezifischer administrierter Starttext mit ausreichender Länge.');$mailer=new MailService($settings,static function(...$args)use(&$mails):void{$mails[]=$args;});$service=new RepresentationRequestContactService($pdo,$requests,$settings,$mailer);$preview=$service->preview((int)$contact['id'],$request['id']);
$check(str_contains($preview['before'],'Hallo Anna')&&str_contains($preview['after'],'Bernd Beta')&&str_contains($preview['after'],'contact@example.test')&&str_contains($preview['after'],'Gesuch Chapter'),'Vorschau enthält feste Pflichtinformationen.');$check(!str_contains($preview['before'].$preview['after'],'owner@example.test'),'Empfänger-E-Mail bleibt privat.');$custom='Hallo, ich übernehme gerne die Vertretung an diesem Termin.';$service->send((int)$contact['id'],$request['id'],$custom);$check(count($mails)===1&&$mails[0][0]==='owner@example.test'&&$mails[0][4]==='contact@example.test'&&str_contains($mails[0][3],$custom),'Empfänger, Reply-To und Freitext korrekt.');
$check($preview['customMessage']==='Gesuchsspezifischer administrierter Starttext mit ausreichender Länge.','Administrierter Gesuch-Starttext wird getrennt geladen.');
$duplicate=false;try{$service->send((int)$contact['id'],$request['id'],$custom);}catch(DomainException){$duplicate=true;}$check($duplicate,'Doppelversandschutz greift.');$own=false;try{$service->preview((int)$owner['id'],$request['id']);}catch(DomainException){$own=true;}$check($own,'Eigenes Gesuch ist nicht kontaktierbar.');
$settings->saveTemplate('representation_request_contact','Antwort {{requested_date}} {{provider_first_name}}',"Hallo {{request_owner_first_name}} {{first_name}},\n\n{{custom_message}}\n\n{{unknown_placeholder}}\n---\nRückmeldung von:\n{{contact_full_name}}\n{{contact_email}}\nBNI-Chapter: {{contact_chapter}}\nVertretung für: {{requested_chapter}}\nTermin: {{requested_date}}");
$anonymousPreview=$service->previewAnonymous((int)$request['id'],'Max','Mustermann','max@example.test');$anonymousRendered=$anonymousPreview['subject'].$anonymousPreview['before'].$anonymousPreview['after'];$check(str_contains($anonymousPreview['before'],'Hallo,')&&!str_contains($anonymousRendered,'Anna')&&!str_contains($anonymousRendered,'{{')&&!str_contains($anonymousRendered,'}}'),'Anonyme Vorschau verwendet neutrale Anrede und enthält keine rohen Platzhalter oder Empfängernamen.');$check(str_contains($anonymousPreview['after'],'Max Mustermann')&&str_contains($anonymousPreview['after'],'max@example.test')&&str_contains($anonymousPreview['after'],'Gesuch Chapter')&&!str_contains($anonymousPreview['after'],'BNI-Chapter:'),'Anonyme Vorschau enthält Pflichtdaten ohne leere Chapterzeile.');
$service->sendAnonymous((int)$request['id'],'Max','Mustermann','max@example.test',$custom,'192.0.2.55');$check(count($mails)===2&&$mails[1][0]==='owner@example.test'&&$mails[1][4]==='max@example.test'&&$mails[1][5]==='Max Mustermann'&&!str_contains($mails[1][2].$mails[1][3],'{{'),'Anonymer Empfänger und Reply-To werden serverseitig bestimmt; Mail enthält keine rohen Platzhalter.');
$anonymousDuplicate=false;try{$service->sendAnonymous((int)$request['id'],'Max','Mustermann','MAX@example.test',$custom,'192.0.2.55');}catch(DomainException){$anonymousDuplicate=true;}$check($anonymousDuplicate,'Anonymer Doppelversandschutz normalisiert die E-Mail-Adresse.');
foreach(range(1,4) as $number)$service->sendAnonymous((int)$request['id'],'Test','Person'.$number,"person{$number}@example.test",$custom,'192.0.2.55');$limited=false;try{$service->sendAnonymous((int)$request['id'],'Noch','Eine','sixth@example.test',$custom,'192.0.2.55');}catch(DomainException){$limited=true;}$check($limited,'Anonymes IP-Limit greift nach fünf gestarteten Anfragen.');
$injection=false;try{$service->sendAnonymous((int)$request['id'],"Max\r\nBcc: bad@example.test",'Mustermann','safe@example.test',$custom,'192.0.2.56');}catch(InvalidArgumentException){$injection=true;}$check($injection,'Header-Injection über Namen wird abgewiesen.');
echo "PASS request contact: authentifiziert und anonym, Vorschau, Datenschutz, Pflichtblock, Reply-To, Deduplizierung und Rate-Limit\n";
