<?php
declare(strict_types=1);
$app=is_file(__DIR__.'/../app/src/Database.php')?__DIR__.'/../app':'/var/www/html';foreach(['Database','UserRepository','RepresentationOfferRepository','RepresentationRequestRepository','RepresentationCleanupService']as$class)require_once"$app/src/$class.php";
$check=static function(bool$c,string$m):void{if(!$c)throw new RuntimeException($m);};$pdo=(new Database(':memory:'))->connection();$now=gmdate('Y-m-d\TH:i:s\Z');$zone=new DateTimeZone('Europe/Berlin');$today=(new DateTimeImmutable('today',$zone))->format('Y-m-d');$past=(new DateTimeImmutable('yesterday',$zone))->format('Y-m-d');$future=(new DateTimeImmutable('tomorrow',$zone))->format('Y-m-d');
$pdo->exec("INSERT INTO organizations(org_id,org_type,chapter_name,meeting_day,timezone,created_at,updated_at)VALUES(1,'CHAPTER','Test','Montag','Europe/Berlin','$now','$now')");$users=new UserRepository($pdo);$user=$users->create('Test','User','cleanup@example.test',password_hash('password1',PASSWORD_DEFAULT),1);$pdo->exec("UPDATE users SET status='active',email_verified_at='$now'");
$insert=$pdo->prepare('INSERT INTO representation_requests(user_id,org_id,request_date,created_at,updated_at)VALUES(?,?,?,?,?)');foreach([$past,$today,$future]as$date)$insert->execute([$user['id'],1,$date,$now,$now]);
$offers=new RepresentationOfferRepository($pdo);$mixed=$offers->createMany((int)$user['id'],[1],false,[$past,$future])[0];$expired=$offers->createMany((int)$user['id'],[1],false,[$past])[0];$always=$offers->createMany((int)$user['id'],[1],true,[])[0];
$pdo->prepare("INSERT INTO representation_contact_log(requester_user_id,offer_id,recipient_user_id,requested_date,sent_at,status)VALUES(?,?,?,?,?,'success')")->execute([$user['id'],$expired,$user['id'],$past,$now]);$result=(new RepresentationCleanupService($pdo))->runCleanup();
$check($result===['requests'=>1,'offerDates'=>2,'offers'=>1],'Cleanup-Zähler korrekt.');$remaining=$pdo->query('SELECT request_date FROM representation_requests ORDER BY request_date')->fetchAll(PDO::FETCH_COLUMN);$check($remaining===[$today,$future],'Heute und Zukunft bleiben, Vergangenheit wird gelöscht.');
$check((int)$pdo->query("SELECT COUNT(*) FROM representation_offer_dates WHERE offer_id=$mixed AND offer_date='$future'")->fetchColumn()===1,'Zukunftstermin im gemischten Angebot bleibt.');$check((int)$pdo->query("SELECT COUNT(*) FROM representation_offers WHERE id=$expired")->fetchColumn()===0,'Leeres datumsgebundenes Angebot wird gelöscht.');$check((int)$pdo->query("SELECT COUNT(*) FROM representation_offers WHERE id=$always")->fetchColumn()===1,'Immer-Angebot bleibt erhalten.');
$history=$pdo->query('SELECT COUNT(*) AS total, SUM(offer_id IS NULL) AS detached FROM representation_contact_log')->fetch();$check((int)$history['total']===1&&(int)$history['detached']===1,'Kontakt-Historie bleibt mit gelöster Angebotsreferenz erhalten.');
echo "PASS representation cleanup: Gesuche, Angebotstermine, leere Angebote und Immer\n";
