<?php
declare(strict_types=1);
$app=is_file(__DIR__.'/../app/src/Database.php')?__DIR__.'/../app':'/var/www/html';foreach(['Database','UserRepository','RepresentationOfferRepository','RepresentationRequestRepository','RepresentationCleanupService']as$class)require_once"$app/src/$class.php";
$check=static function(bool$c,string$m):void{if(!$c)throw new RuntimeException($m);};$pdo=(new Database(':memory:'))->connection();$now=gmdate('Y-m-d\TH:i:s\Z');$zone=new DateTimeZone('Europe/Berlin');$today=(new DateTimeImmutable('today',$zone))->format('Y-m-d');$past=(new DateTimeImmutable('last monday',$zone))->format('Y-m-d');$future=(new DateTimeImmutable('next monday',$zone))->format('Y-m-d');
$pdo->exec("INSERT INTO organizations(org_id,org_type,chapter_name,meeting_day,timezone,created_at,updated_at)VALUES(1,'CHAPTER','Test','Montag','Europe/Berlin','$now','$now')");$users=new UserRepository($pdo);$user=$users->create('Test','User','cleanup@example.test',password_hash('password1',PASSWORD_DEFAULT),1);$pdo->exec("UPDATE users SET status='active',email_verified_at='$now'");
$insert=$pdo->prepare('INSERT INTO representation_requests(user_id,org_id,request_date,created_at,updated_at)VALUES(?,?,?,?,?)');foreach([$past,$today,$future]as$date)$insert->execute([$user['id'],1,$date,$now,$now]);
$offers=new RepresentationOfferRepository($pdo);$mixed=$offers->createMany((int)$user['id'],[1],false,[$past,$future])[0];$expired=$offers->createMany((int)$user['id'],[1],false,[$past])[0];$always=$offers->createMany((int)$user['id'],[1],true,[])[0];
$pdo->prepare("INSERT INTO representation_contact_log(requester_user_id,offer_id,recipient_user_id,requested_date,sent_at,status)VALUES(?,?,?,?,?,'success')")->execute([$user['id'],$expired,$user['id'],$past,$now]);$result=(new RepresentationCleanupService($pdo))->runCleanup();
$check($result===['requests'=>0,'offerDates'=>0,'offers'=>0],'Historienerhalt meldet keine physischen Löschungen.');$check((int)$pdo->query('SELECT COUNT(*) FROM representation_requests')->fetchColumn()===3&&(int)$pdo->query('SELECT COUNT(*) FROM representation_offer_dates')->fetchColumn()===3&&(int)$pdo->query('SELECT COUNT(*) FROM representation_offers')->fetchColumn()===3,'Abgelaufene Gesuche, Angebotstermine oder Angebote wurden physisch gelöscht.');
echo "PASS representation cleanup: Historische Gesuche und Angebote bleiben erhalten\n";
