<?php
declare(strict_types=1);
$app=is_file(__DIR__.'/../app/src/Database.php')?__DIR__.'/../app':'/var/www/html'; foreach(['Database','UserRepository','MailSettingsRepository','MailService','RepresentationOfferRepository','RepresentationContactService'] as $class)require_once "$app/src/$class.php";
$check=static function(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}; $pdo=(new Database(':memory:'))->connection();$now=gmdate('Y-m-d\TH:i:s\Z');
$pdo->exec("INSERT INTO organizations(org_id,org_type,chapter_name,meeting_day,created_at,updated_at)VALUES(101,'CHAPTER','Chapter X','Freitag','$now','$now'),(202,'CHAPTER','Chapter Y','Montag','$now','$now')");
$users=new UserRepository($pdo);$a=$users->create('Anna','Alpha','anna@example.test',password_hash('password1',PASSWORD_DEFAULT),101);$b=$users->create('Bernd','Beta','bernd@example.test',password_hash('password2',PASSWORD_DEFAULT),202);$pdo->exec("UPDATE users SET status='active',email_verified_at='$now'");
$offers=new RepresentationOfferRepository($pdo);$future=(new DateTimeImmutable('next friday',new DateTimeZone('Europe/Berlin')))->format('Y-m-d');$always=$offers->createMany((int)$b['id'],[101],true,[])[0];$dated=$offers->createMany((int)$b['id'],[101],false,[$future])[0];
$mails=[];$settings=new MailSettingsRepository($pdo);$mailer=new MailService($settings,static function(...$args)use(&$mails):void{$mails[]=$args;});$service=new RepresentationContactService($pdo,$offers,$settings,$mailer);$text='Hallo, bitte melde dich wegen der Vertretung bei mir.';
$settings->saveCustomMessages('Angebotsspezifischer administrierter Starttext mit ausreichender Länge.','Gesuchsspezifischer administrierter Starttext mit ausreichender Länge.');
$settings->saveTemplate('representation_contact','Anfrage {{requested_date}} {{unknown_subject}}',"Hallo {{provider_first_name}} {{first_name}},\n\n{{custom_message}}\n\n{{unknown_body}}\n---\nAnfrage von:\n{{requester_full_name}}\n{{requester_email}}\nChapter: {{requester_chapter}}\nTermin: {{requested_date}}");
$preview=$service->preview((int)$a['id'],$dated,$future);$check(str_contains($preview['before'],'Hallo Bernd')&&str_contains($preview['after'],'Anna Alpha')&&str_contains($preview['after'],'anna@example.test')&&str_contains($preview['after'],'Chapter X'),'Vollständige Mailvorschau mit Pflichtblock.');$check(!str_contains($preview['before'].$preview['after'],'bernd@example.test'),'Empfänger-E-Mail nicht in Vorschau.');
$check(!str_contains($preview['subject'].$preview['before'].$preview['after'],'{{'),'Auch eingeloggte Vorschau enthält keine rohen Platzhalter.');
$check($preview['customMessage']==='Angebotsspezifischer administrierter Starttext mit ausreichender Länge.','Administrierter Angebot-Starttext wird geladen.');
$service->send((int)$a['id'],$dated,$future,$text);$check(count($mails)===1&&$mails[0][0]==='bernd@example.test'&&$mails[0][4]==='anna@example.test','Empfänger und Reply-To serverseitig.');$check(str_contains($mails[0][3],'Anna Alpha')&&str_contains($mails[0][3],'Chapter X')&&str_contains($mails[0][3],$text)&&!str_contains($mails[0][2].$mails[0][3],'{{'),'Pflichtblock und Nachricht enthalten; Versand ohne rohe Platzhalter.');
$duplicate=false;try{$service->send((int)$a['id'],$dated,$future,$text);}catch(DomainException){$duplicate=true;}$check($duplicate&&count($mails)===1,'Doppelversandschutz vor Mailversand.');
$wrong=(new DateTimeImmutable($future))->modify('+1 day')->format('Y-m-d');$rejected=false;try{$service->send((int)$a['id'],$always,$wrong,$text);}catch(InvalidArgumentException){$rejected=true;}$check($rejected,'Immer-Angebot nur am Meeting-Wochentag.');
$discovery=$offers->findForHomeChapter(101,(int)$a['id'],(new DateTimeImmutable('today',new DateTimeZone('Europe/Berlin')))->format('Y-m-d'));$check(count($discovery['datedOffers'])===1&&count($discovery['datedOffers'][0]['providers'])===1&&count($discovery['allDatesOffers'])===1,'Immer-Anbieter ergänzt Termin ohne Personendublette.');
echo "PASS representation contact: Struktur, Datenschutz, Mail, Pflichtdaten, Reply-To, Deduplizierung und Wochentag\n";
