#!/usr/bin/env python3
import json, os, time, urllib.request
BASE='http://127.0.0.1:9516'; CHAPTER_IDS=[int(value) for value in os.environ['CHAPTER_IDS'].split(',')]; SEARCH_LOCATION=os.environ.get('SEARCH_LOCATION','Köln')
def request(method,path,payload=None):
    req=urllib.request.Request(BASE+path,data=None if payload is None else json.dumps(payload).encode(),method=method,headers={'Content-Type':'application/json'})
    with urllib.request.urlopen(req) as response:return json.loads(response.read())['value']
session=request('POST','/session',{'capabilities':{'alwaysMatch':{'browserName':'chrome','goog:chromeOptions':{'args':['--headless','--no-sandbox','--disable-gpu','--window-size=1440,1000']},'goog:loggingPrefs':{'browser':'ALL','performance':'ALL'}}}})['sessionId']
def script(source):return request('POST',f'/session/{session}/execute/sync',{'script':source,'args':[]})
def login(email):
    request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=login'});time.sleep(.3)
    script(f"const f=document.querySelector('#login-form');f.login.value='{email}';f.password.value='representation-test-123';f.requestSubmit();");time.sleep(.6)
try:
    login('representation-c@example.invalid'); request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=vertretung-finden'});time.sleep(.4)
    request('POST',f'/session/{session}/log',{'type':'performance'})
    no_home=script("return {hint:document.body.textContent.includes('noch kein Heimatchapter hinterlegt'),list:!!document.querySelector('#available-representations')};")
    assert no_home['hint'] and not no_home['list']
    assert not [entry for entry in request('POST',f'/session/{session}/log',{'type':'performance'}) if '/api/representation/find.php' in entry.get('message','')]
    script("document.querySelector('#logout-button').click()");time.sleep(.4)
    login('representation-b@example.invalid'); request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=vertretung'});time.sleep(.8)
    setup=script("const rows=[...document.querySelectorAll('#representation-list input[data-org-id]')],own=rows.find(x=>x.disabled);return {own:Number(own.dataset.orgId),ownMarked:own.closest('tr').textContent.includes('Heimatchapter'),redundant:!!document.querySelector('.representation-save-panel h2')};")
    assert setup['ownMarked'] and not setup['redundant']
    own_rejected=script(f"""const token=document.querySelector('meta[name="csrf-token"]').content;return fetch('/api/representation/offers.php',{{method:'POST',headers:{{'Content-Type':'application/json','X-CSRF-Token':token}},body:JSON.stringify({{orgIds:[{CHAPTER_IDS[0]},{setup['own']}],allDates:true,dates:[]}})}}).then(async r=>({{status:r.status,payload:await r.json()}}));""")
    assert own_rejected['status']==400 and 'eigenes Chapter' in own_rejected['payload']['error']
    assert script("return document.querySelectorAll('#representation-own-list .representation-offer-card').length;")==0
    ids=json.dumps(CHAPTER_IDS)
    script(f"for(const id of {ids})document.querySelector('input[data-org-id=\"'+id+'\"]').click();document.querySelector('#representation-all-dates').click();document.querySelector('#save-representation-offer').click();");time.sleep(.7)
    saved=script("return {message:document.querySelector('#representation-save-message').textContent,cards:[...document.querySelectorAll('#representation-own-list .representation-offer-card')].map(x=>({heading:x.querySelector('h3').textContent,badges:x.querySelectorAll('.date-chip').length}))};")
    assert saved['message']=='3 Vertretungsangebote gespeichert.' and len(saved['cards'])==3 and all(x['badges']==1 for x in saved['cards']),saved
    duplicate=script(f"""const token=document.querySelector('meta[name="csrf-token"]').content;return fetch('/api/representation/offers.php',{{method:'POST',headers:{{'Content-Type':'application/json','X-CSRF-Token':token}},body:JSON.stringify({{orgIds:[{CHAPTER_IDS[0]}],allDates:true,dates:[]}})}}).then(async r=>({{status:r.status,payload:await r.json()}}));""")
    assert duplicate['status']==409 and 'identisches' in duplicate['payload']['error']
    request('POST',f'/session/{session}/log',{'type':'performance'})
    dialog=script("document.querySelector('#representation-own-list button[data-delete-offer]').click();const d=document.querySelector('#delete-representation-dialog');return {open:d.open,title:d.querySelector('h2').textContent,aria:d.getAttribute('aria-modal')};")
    assert dialog['open'] and dialog['title']=='Vertretungsangebot löschen' and dialog['aria']=='true'
    script("document.querySelector('#cancel-delete-representation').click()");time.sleep(.2)
    assert script("return !document.querySelector('#delete-representation-dialog').open&&document.querySelectorAll('#representation-own-list .representation-offer-card').length===3;")
    cancel_network=request('POST',f'/session/{session}/log',{'type':'performance'});assert not [x for x in cancel_network if '/api/representation/offers.php' in x.get('message','')]
    script("document.querySelector('#representation-own-list button[data-delete-offer]').click();document.querySelector('#delete-representation-dialog').dispatchEvent(new Event('cancel',{cancelable:true}));")
    assert not script("return document.querySelector('#delete-representation-dialog').open;")
    for expected in [2,1,0]:
        script("document.querySelector('#representation-own-list button[data-delete-offer]').click();document.querySelector('#confirm-delete-representation').click();");time.sleep(.5)
        assert script("return document.querySelectorAll('#representation-own-list .representation-offer-card').length;")==expected
    for chapter_id in CHAPTER_IDS[:2]:script(f"document.querySelector('input[data-org-id=\"{chapter_id}\"]').click();")
    for date in ['21.08.2099','28.08.2099']:script(f"const i=document.querySelector('#representation-date');i.value='{date}';i.dispatchEvent(new Event('input',{{bubbles:true}}));")
    script("document.querySelector('#save-representation-offer').click()");time.sleep(.7)
    dated=script("return [...document.querySelectorAll('#representation-own-list .representation-offer-card')].map(x=>({heading:x.querySelector('h3').textContent,dates:x.querySelectorAll('.date-chip').length}));")
    assert len(dated)==2 and all(x['dates']==2 for x in dated),dated
    always_added=script(f"""const token=document.querySelector('meta[name="csrf-token"]').content;return fetch('/api/representation/offers.php',{{method:'POST',headers:{{'Content-Type':'application/json','X-CSRF-Token':token}},body:JSON.stringify({{orgIds:[{CHAPTER_IDS[0]}],allDates:true,dates:[]}})}}).then(async r=>({{status:r.status,payload:await r.json()}}));""")
    assert always_added['status']==201,always_added
    script("document.querySelector('#logout-button').click()");time.sleep(.4);login('representation-a@example.invalid')
    assert 'Vertretung finden' in script("return [...document.querySelectorAll('nav a')].map(x=>x.textContent.trim());")
    request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=vertretung-finden'});time.sleep(.7)
    found=script("const dated=document.querySelector('#dated-representations');return {dates:dated.querySelectorAll('.representation-date-group').length,cards:dated.querySelectorAll('.representation-provider-card').length,text:dated.textContent,email:document.body.textContent.includes('representation-b@example.invalid'),orgId:/orgId/i.test(document.body.textContent)};")
    assert found['dates']==2 and found['cards']==2 and 'Bernd B.' in found['text'] and not found['email'] and not found['orgId'],found
    assert script("return document.querySelectorAll('#all-date-representations .representation-provider-card').length;")==1
    overview=script("return {cards:document.querySelectorAll('#representation-offers-overview .representation-offer-card').length,buttons:[...document.querySelectorAll('#representation-offers-overview .representation-offer-card')].map(x=>x.querySelectorAll('.contact-provider').length),dateType:document.querySelector('#representation-request-date').type,dayHint:document.querySelector('#representation-request-day-hint').textContent};")
    assert overview['cards']==2 and overview['buttons']==[1,1] and overview['dateType']=='text' and 'freitags' in overview['dayHint'],overview
    multiple=script("document.querySelector('#representation-offers-overview .representation-offer-card .contact-provider').click();return {open:document.querySelector('#representation-contact-dialog').open,options:document.querySelectorAll('#representation-contact-date-options input').length,hidden:document.querySelector('#representation-contact-date-options').hidden};")
    assert multiple=={'open':True,'options':2,'hidden':False},multiple
    script("document.querySelector('#cancel-representation-contact').click();")
    request_dates=script("const d=new Date();const next=(from,day)=>{const x=new Date(from);x.setHours(12,0,0,0);x.setDate(x.getDate()+((day-x.getDay()+7)%7));return x};const f1=next(d,5),f2=new Date(f1);f2.setDate(f1.getDate()+7);const w=next(d,3);return [f1,f2,w].map(x=>x.toISOString().slice(0,10));")
    for value in request_dates[:2]:
        script(f"const i=document.querySelector('#representation-request-date'),p='{value}'.split('-');i.value=p[2]+'.'+p[1]+'.'+p[0];i.dispatchEvent(new Event('input',{{bubbles:true}}));");time.sleep(.5)
    request_state=script("return {chips:[...document.querySelectorAll('#representation-request-chips .date-chip')].map(x=>x.textContent.trim()),loading:document.body.textContent.includes('Vertretungsangebote werden geladen …')};")
    assert len(request_state['chips'])==2 and not request_state['loading'],request_state
    merged=script("return [...document.querySelectorAll('#dated-representations .representation-date-group')].slice(0,2).every(group=>group.querySelectorAll('.representation-provider-card').length===1);")
    assert merged
    client_invalid=script(f"const i=document.querySelector('#representation-request-date'),p='{request_dates[2]}'.split('-');i.value=p[2]+'.'+p[1]+'.'+p[0];i.dispatchEvent(new Event('input',{{bubbles:true}}));return {{invalid:i.getAttribute('aria-invalid'),message:document.querySelector('#representation-request-date-error').textContent}};")
    assert client_invalid['invalid']=='true' and 'Freitag' in client_invalid['message'],client_invalid
    invalid_request=script(f"""const token=document.querySelector('meta[name="csrf-token"]').content;return fetch('/api/representation/requests.php',{{method:'POST',headers:{{'Content-Type':'application/json','X-CSRF-Token':token}},body:JSON.stringify({{request_date:'{request_dates[2]}'}})}}).then(async r=>({{status:r.status,payload:await r.json()}}));""")
    assert invalid_request['status']==400 and 'Meeting-Wochentag' in invalid_request['payload']['error'],invalid_request
    script("document.querySelector('#representation-request-chips button').click();");time.sleep(.5)
    assert script("return document.querySelectorAll('#representation-request-chips .date-chip').length;")==1
    script("document.querySelector('#dated-representations .contact-provider').click();");time.sleep(.5)
    contact=script("const d=document.querySelector('#representation-contact-dialog');return {open:d.open,fixed:document.querySelector('#representation-contact-fixed-date').textContent,dateHidden:document.querySelector('#representation-contact-date-label').hidden,hint:document.querySelector('#representation-contact-hint').textContent,message:document.querySelector('#representation-contact-message').value,before:document.querySelector('#representation-contact-before').textContent,after:document.querySelector('#representation-contact-after').textContent,subject:document.querySelector('#representation-contact-subject').textContent};")
    assert contact['open'] and contact['dateHidden'] and 'Termin:' in contact['fixed'] and 'eMail Adresse' in contact['hint'] and len(contact['message'])>=20 and 'Anna Alpha' in contact['after'] and 'representation-a@example.invalid' in contact['after'] and 'Betreff:' in contact['subject'],contact
    script("document.querySelector('#cancel-representation-contact').click()")
    script("document.querySelector('#logout-button').click()");time.sleep(.4);login('representation-d@example.invalid');request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=vertretung-finden'});time.sleep(.5)
    script(f"const i=document.querySelector('#representation-request-date'),p='{request_dates[1]}'.split('-');i.value=p[2]+'.'+p[1]+'.'+p[0];i.dispatchEvent(new Event('input',{{bubbles:true}}));");time.sleep(.5);script("document.querySelector('#logout-button').click()");time.sleep(.4);request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=crosschaptern'});time.sleep(.4)
    location=json.dumps(SEARCH_LOCATION);script(f"const f=document.querySelector('#chapter-search-form');document.querySelector('#search-location').value={location};f.querySelector('[data-limit=\"all\"]').click();f.requestSubmit();");time.sleep(1.5)
    anonymous=script(f"const c=document.querySelector('#result-{CHAPTER_IDS[0]}');return c?{{text:c.querySelector('.result-representation-requests')?.textContent||'',buttons:c.querySelectorAll('.request-contact-button').length}}:null;")
    assert anonymous and 'Person 1' in anonymous['text'] and 'Person 2' in anonymous['text'] and 'Anna' not in anonymous['text'] and 'Dora' not in anonymous['text'] and anonymous['buttons']==2 and '@' not in anonymous['text'],anonymous
    script(f"document.querySelector('#result-{CHAPTER_IDS[0]} .request-contact-button').click();");time.sleep(.4)
    anonymous_dialog=script("const fields=document.querySelector('#anonymous-request-contact-fields');return {open:document.querySelector('#request-contact-dialog').open,login:location.search.includes('view=login'),fields:!fields.hidden,visibleFields:[...fields.querySelectorAll('input')].filter(input=>getComputedStyle(input).display!=='none'&&input.getClientRects().length>0).length,display:getComputedStyle(fields).display,message:document.querySelector('#request-contact-message').value};")
    assert anonymous_dialog['open'] and not anonymous_dialog['login'] and anonymous_dialog['fields'] and anonymous_dialog['visibleFields']==3 and anonymous_dialog['display']=='grid' and len(anonymous_dialog['message'])>=20,anonymous_dialog
    invalid_mail=script("const e=document.querySelector('#request-contact-email');e.value='ungueltig';e.dispatchEvent(new Event('blur',{bubbles:true}));return {invalid:e.getAttribute('aria-invalid'),text:document.querySelector('#request-contact-email-error').textContent};")
    assert invalid_mail['invalid']=='true' and 'gültige E-Mail' in invalid_mail['text'],invalid_mail
    script("const f=document.querySelector('#request-contact-form');document.querySelector('#request-contact-first-name').value='Max';document.querySelector('#request-contact-last-name').value='Mustermann';document.querySelector('#request-contact-email').value='max@example.test';document.querySelector('#request-contact-email').dispatchEvent(new Event('blur',{bubbles:true}));");time.sleep(.5)
    anonymous_preview=script("const text=document.querySelector('#request-contact-content').textContent;return {after:document.querySelector('#request-contact-after').textContent,recipient:text.includes('representation-a@example.invalid'),owner:text.includes('Anna'),raw:text.includes('{{')||text.includes('}}')};")
    assert 'Max Mustermann' in anonymous_preview['after'] and 'max@example.test' in anonymous_preview['after'] and not anonymous_preview['recipient'] and not anonymous_preview['owner'] and not anonymous_preview['raw'],anonymous_preview
    script("document.querySelector('#cancel-request-contact').click()");
    login('representation-b@example.invalid');request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=crosschaptern'});time.sleep(.4);request('POST',f'/session/{session}/log',{'type':'performance'});script(f"const f=document.querySelector('#chapter-search-form');document.querySelector('#search-location').value={location};f.querySelector('[data-limit=\"all\"]').click();f.requestSubmit();");time.sleep(1.5)
    logged=script(f"const c=document.querySelector('#result-{CHAPTER_IDS[0]}');return c?{{text:c.querySelector('.result-representation-requests')?.textContent||'',buttons:c.querySelectorAll('.request-contact-button').length,email:c.textContent.includes('representation-a@example.invalid')}}:null;")
    assert logged and 'Anna A.' in logged['text'] and 'Dora D.' in logged['text'] and logged['buttons']==2 and not logged['email'],logged
    search_network=request('POST',f'/session/{session}/log',{'type':'performance'});messages=[json.loads(x['message'])['message'] for x in search_network];urls=[x['params']['request']['url'] for x in messages if x['method']=='Network.requestWillBeSent'];assert len([x for x in urls if '/api/search.php' in x])==1 and not [x for x in urls if '/api/representation/' in x] and not [x for x in urls if 'bni.de' in x],urls
    ownership_b=script(f"""const headers={{'Content-Type':'application/json','X-CSRF-Token':document.querySelector('meta[name=\"csrf-token\"]').content}};return Promise.all([fetch('/api/auth/status.php').then(r=>r.json()),fetch('/api/search.php',{{method:'POST',headers,body:JSON.stringify({{location:{location},days:[],time:'any',sort:'distance',limit:'all'}})}}).then(r=>r.json())]).then(([auth,search])=>{{const chapter=search.results.find(item=>item.orgId==={CHAPTER_IDS[0]});const own=chapter.representationRequests.find(item=>item.displayName==='Anna A.');return {{viewerUserId:auth.user.user_id,request:own}};}});""")
    assert ownership_b['request']['isOwn'] is False and ownership_b['request']['canContact'] is True and ownership_b['request']['requestId']>0,ownership_b
    script(f"document.querySelector('#result-{CHAPTER_IDS[0]} .request-contact-button').click();");time.sleep(.5)
    request_preview=script("const fields=document.querySelector('#anonymous-request-contact-fields');return {open:document.querySelector('#request-contact-dialog').open,before:document.querySelector('#request-contact-before').textContent,after:document.querySelector('#request-contact-after').textContent,email:document.querySelector('#request-contact-content').textContent.includes('representation-a@example.invalid'),anonymousFields:!fields.hidden,visibleFields:[...fields.querySelectorAll('input')].filter(input=>getComputedStyle(input).display!=='none'&&input.getClientRects().length>0).length,display:getComputedStyle(fields).display};")
    assert request_preview['open'] and 'Hallo Anna' in request_preview['before'] and 'Bernd Beta' in request_preview['after'] and not request_preview['email'] and not request_preview['anonymousFields'] and request_preview['visibleFields']==0 and request_preview['display']=='none',request_preview
    contact_network=request('POST',f'/session/{session}/log',{'type':'performance'});contact_messages=[json.loads(x['message'])['message'] for x in contact_network];contact_urls=[x['params']['request']['url'] for x in contact_messages if x['method']=='Network.requestWillBeSent'];assert len([x for x in contact_urls if '/api/representation/request-contact.php' in x])==1 and not [x for x in contact_urls if '/api/auth/login.php' in x],contact_urls
    script("document.querySelector('#cancel-request-contact').click();document.querySelector('#logout-button').click()");time.sleep(.4);login('representation-a@example.invalid');request('POST',f'/session/{session}/url',{'url':'http://localhost:8082/?view=crosschaptern'});time.sleep(.4);script(f"const f=document.querySelector('#chapter-search-form');document.querySelector('#search-location').value={location};f.querySelector('[data-limit=\"all\"]').click();f.requestSubmit();");time.sleep(1.5)
    ownership_a=script(f"""const headers={{'Content-Type':'application/json','X-CSRF-Token':document.querySelector('meta[name=\"csrf-token\"]').content}};return Promise.all([fetch('/api/auth/status.php').then(r=>r.json()),fetch('/api/search.php',{{method:'POST',headers,body:JSON.stringify({{location:{location},days:[],time:'any',sort:'distance',limit:'all'}})}}).then(r=>r.json())]).then(([auth,search])=>{{const chapter=search.results.find(item=>item.orgId==={CHAPTER_IDS[0]});const own=chapter.representationRequests.find(item=>item.displayName==='Anna A.');const row=[...document.querySelectorAll('#result-{CHAPTER_IDS[0]} .result-representation-request')].find(item=>item.textContent.includes('Anna A.'));return {{viewerUserId:auth.user.user_id,request:own,rowText:row?.textContent||'',buttons:row?.querySelectorAll('.request-contact-button').length||0}};}});""")
    assert ownership_a['request']['isOwn'] is True and ownership_a['request']['canContact'] is False and 'requestId' not in ownership_a['request'] and 'Dein Gesuch' in ownership_a['rowText'] and ownership_a['buttons']==0,ownership_a
    logs=request('POST',f'/session/{session}/log',{'type':'browser'});assert not [x for x in logs if x.get('level')=='SEVERE' and '/api/representation/offers.php' not in x.get('message','') and '/api/representation/requests.php' not in x.get('message','')],logs
    print('PASS Chromium ownership:',json.dumps({'foreign':ownership_b,'own':ownership_a},ensure_ascii=False))
finally:request('DELETE',f'/session/{session}')
