<?php
declare(strict_types=1);
$root=is_file(__DIR__.'/../app/src/Database.php')?__DIR__.'/../app':'/var/www/html';foreach(['Database','MailSettingsRepository','MailService','AutomationConfig','WatchlistRepository','WatchlistNotificationRunner']as$file)require_once$root.'/src/'.$file.'.php';
$check=static function(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);};$path=tempnam(sys_get_temp_dir(),'watchlist-');
try{$db=(new Database($path))->connection();$stamp='2026-10-13T08:00:00Z';$org=$db->prepare("INSERT INTO organizations(org_id,org_type,chapter_name,city,short_link_slug,created_at,updated_at)VALUES(?,?,?,?,?,?,?)");$org->execute([101,'CHAPTER','Balthasar BNI','Köln','bni_balthasar',$stamp,$stamp]);$org->execute([102,'REGION','Region',null,null,$stamp,$stamp]);
$user=$db->prepare("INSERT INTO users(first_name,last_name,email,password_hash,role,status,email_verified_at,created_at,updated_at)VALUES(?,?,?,'x',?,'active',?,?,?)");foreach([['Anna','Watcher','anna@example.test','user'],['Max','Creator','max@example.test','user'],['Mara','Manager','mara@example.test','user_manager']]as$row)$user->execute([$row[0],$row[1],$row[2],$row[3],$stamp,$stamp,$stamp]);
$repo=new WatchlistRepository($db);$check($repo->add(1,101)&&!$repo->add(1,101),'Add/Dublettenschutz fehlerhaft.');try{$repo->add(1,102);throw new RuntimeException('Region akzeptiert.');}catch(InvalidArgumentException){}$repo->add(3,101);$check($repo->organizationIds(3)===[101],'user_manager fehlerhaft.');
$request=$db->prepare('INSERT INTO representation_requests(user_id,org_id,request_date,created_at,updated_at)VALUES(2,101,?,?,?)');$request->execute(['2026-10-13','2026-10-13T07:01:00Z',$stamp]);$before=$repo->accountData(1,new DateTimeImmutable('2026-10-13 09:59:59',new DateTimeZone('Europe/Berlin')));$after=$repo->accountData(1,new DateTimeImmutable('2026-10-13 10:00:00',new DateTimeZone('Europe/Berlin')));$check(count($before['requests'])===1&&$before['requests'][0]['chapterLink']==='/bni_balthasar'&&$after['requests']===[],'Ablaufgrenze/Shortlink fehlerhaft.');
$repo->setEmailNotifications(1,true);$db->exec("UPDATE users SET watchlist_email_enabled_at='2026-10-13T07:00:30Z' WHERE id=1");$sent=[];$settings=new MailSettingsRepository($db);$mail=new MailService($settings,static function(...$args)use(&$sent):void{$sent[]=$args;});$runner=new WatchlistNotificationRunner($db,$mail);$check($runner->run(new DateTimeImmutable('2026-10-13T07:02:00Z'))['sent']===1&&count($sent)===1,'Mail fehlt.');$db->exec("UPDATE automation_runtime SET last_watchlist_notification_check_at='2026-10-13T07:00:00Z'");$runner->run(new DateTimeImmutable('2026-10-13T08:40:00Z'));$check(count($sent)===1&&!$runner->run(new DateTimeImmutable('2026-10-13T08:50:00Z'))['ran'],'Deduplizierung/Intervall fehlerhaft.');
$request->execute(['2026-10-20','2026-10-13T08:45:00Z',$stamp]);$own=$db->prepare('INSERT INTO representation_requests(user_id,org_id,request_date,created_at,updated_at)VALUES(1,101,?,?,?)');$own->execute(['2026-10-27','2026-10-13T08:46:00Z',$stamp]);$db->exec("UPDATE automation_runtime SET last_watchlist_notification_check_at='2026-10-13T07:00:00Z'");$failure=new WatchlistNotificationRunner($db,new MailService($settings,static function():void{throw new RuntimeException('mock');}));$check($failure->run(new DateTimeImmutable('2026-10-13T09:20:00Z'))['failed']===1,'Mailfehler fehlt.');$db->exec("UPDATE automation_runtime SET last_watchlist_notification_check_at='2026-10-13T07:00:00Z'");$runner->run(new DateTimeImmutable('2026-10-13T10:00:00Z'));$check(count($sent)===2&&(int)$db->query('SELECT COUNT(*) FROM watchlist_notifications')->fetchColumn()===2,'Retry/Selbstmail fehlerhaft.');
$repo->setEmailNotifications(1,false);$check(!$repo->accountData(1)['emailNotifications']&&$repo->organizationIds(1)===[101],'Deaktivierung fehlerhaft.');$repo->remove(1,101);$check($repo->organizationIds(1)===[],'Remove fehlerhaft.');echo"PASS Watchlist, Ablaufgrenze, Intervall und Mail-Deduplizierung\n";}finally{if(is_string($path)){@unlink($path);@unlink($path.'-wal');@unlink($path.'-shm');}}
