<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/src/AccountFactory.php'; require_once dirname(__DIR__, 2) . '/src/AccountService.php'; require_once dirname(__DIR__, 2) . '/src/Auth.php'; require_once dirname(__DIR__, 2) . '/src/ClientIp.php'; require_once dirname(__DIR__, 2) . '/src/Database.php'; require_once dirname(__DIR__, 2) . '/src/JsonResponse.php'; require_once dirname(__DIR__, 2) . '/src/MailService.php'; require_once dirname(__DIR__, 2) . '/src/MailSettingsRepository.php'; require_once dirname(__DIR__, 2) . '/src/UserRepository.php'; require_once dirname(__DIR__, 2) . '/src/UserFacingErrorLogger.php';
if ($_SERVER['REQUEST_METHOD'] !== 'POST') JsonResponse::send(['error' => 'Nur POST ist erlaubt.'], 405); Auth::requireCsrfJson();
$payload=[];
try { $payload = json_decode(file_get_contents('php://input') ?: '', true, 32, JSON_THROW_ON_ERROR);if(!is_array($payload))throw new JsonException('Ungültige Anfrage.'); AccountFactory::create()['service']->register($payload, ClientIp::address());JsonResponse::send(['registered' => true, 'mailSent' => true, 'code'=>'registered','message' => 'Bitte bestätige deine E-Mail-Adresse.']); }
catch (JsonException|InvalidArgumentException $e) { JsonResponse::send(['error' => $e->getMessage()], 400); }
catch (DomainException $e) { JsonResponse::send(['error' => $e->getMessage()], str_starts_with($e->getMessage(), 'Zu viele BNI-Mitgliederprüfungen') ? 429 : 409); }
catch (RegistrationException $e) { (new UserFacingErrorLogger((new Database())->connection()))->log($e->getMessage(),$e->technicalReason,$e->reason,'registration',null,'/api/auth/register.php');JsonResponse::send(['error' => $e->getMessage(), 'code' => $e->reason], 503); }
catch (HomeChapterVerificationException $e) { $home=(int)($payload['home_chapter_org_id']??0);$technical=$e->reason==='ambiguous'?"Multiple member matches for chapter org_id={$home}":'BNI member verification failed: '.($e->technicalReason??$e->reason);if(in_array($e->reason,['ambiguous','technical_unavailable'],true))(new UserFacingErrorLogger((new Database())->connection()))->log($e->getMessage(),$technical,$e->reason,'registration',null,'/api/auth/register.php');JsonResponse::send(['error'=>$e->getMessage(),'message'=>$e->getMessage(),'code'=>$e->reason,'technicalReason'=>$e->technicalReason,'canSkip'=>false],$e->reason==='technical_unavailable'?503:422); }
catch (RuntimeException $e) { $public=str_starts_with($e->getMessage(),'Die BNI-Mitgliederprüfung')?$e->getMessage():'Das Konto konnte nicht angelegt werden.';JsonResponse::send(['error'=>$public],503); }
catch (Throwable) { JsonResponse::send(['error' => 'Das Konto konnte nicht angelegt werden.'], 500); }
