<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/src/AccountFactory.php'; require_once dirname(__DIR__, 2) . '/src/AccountService.php'; require_once dirname(__DIR__, 2) . '/src/Auth.php'; require_once dirname(__DIR__, 2) . '/src/ClientIp.php'; require_once dirname(__DIR__, 2) . '/src/Database.php'; require_once dirname(__DIR__, 2) . '/src/JsonResponse.php'; require_once dirname(__DIR__, 2) . '/src/MailService.php'; require_once dirname(__DIR__, 2) . '/src/MailSettingsRepository.php'; require_once dirname(__DIR__, 2) . '/src/UserRepository.php';
if ($_SERVER['REQUEST_METHOD'] !== 'POST') JsonResponse::send(['error' => 'Nur POST ist erlaubt.'], 405); Auth::requireCsrfJson();
$payload=[];
try { $payload = json_decode(file_get_contents('php://input') ?: '', true, 32, JSON_THROW_ON_ERROR);if(!is_array($payload))throw new JsonException('Ungültige Anfrage.');$home=(int)($payload['home_chapter_org_id']??0);if(($payload['skip_chapter_verification']??false)===true&&(int)($_SESSION['registration_chapter_skip_org_id']??0)!==$home)JsonResponse::send(['error'=>'Die Chapter-Prüfung kann nur nach einem technischen Prüffehler übersprungen werden.','code'=>'skip_not_allowed'],409); AccountFactory::create()['service']->register($payload, ClientIp::address());unset($_SESSION['registration_chapter_skip_org_id']);JsonResponse::send(['registered' => true, 'mailSent' => true, 'code'=>'registered','message' => 'Bitte bestätige deine E-Mail-Adresse.']); }
catch (JsonException|InvalidArgumentException $e) { JsonResponse::send(['error' => $e->getMessage()], 400); }
catch (DomainException $e) { JsonResponse::send(['error' => $e->getMessage()], str_starts_with($e->getMessage(), 'Zu viele BNI-Mitgliederprüfungen') ? 429 : 409); }
catch (RegistrationException $e) { JsonResponse::send(['error' => $e->getMessage(), 'code' => $e->reason], 503); }
catch (HomeChapterVerificationException $e) { if($e->canSkip&&is_array($payload))$_SESSION['registration_chapter_skip_org_id']=(int)($payload['home_chapter_org_id']??0);else unset($_SESSION['registration_chapter_skip_org_id']);JsonResponse::send(['error'=>$e->getMessage(),'message'=>$e->getMessage(),'code'=>$e->reason,'technicalReason'=>$e->technicalReason,'canSkip'=>$e->canSkip],$e->reason==='technical_unavailable'?503:422); }
catch (RuntimeException $e) { $public=str_starts_with($e->getMessage(),'Die BNI-Mitgliederprüfung')?$e->getMessage():'Das Konto konnte nicht angelegt werden.';JsonResponse::send(['error'=>$public],503); }
catch (Throwable) { JsonResponse::send(['error' => 'Das Konto konnte nicht angelegt werden.'], 500); }
