<?php if ($authMode !== 'verified'): ?><section class="page-hero login-hero"><div class="shell"><p class="eyebrow">Benutzerkonto</p><h1><?= $authMode === 'register' ? 'Neues Konto anlegen' : ($authMode === 'forgot' ? 'Passwort zurücksetzen' : 'Anmelden') ?></h1><p>Verwalte dein persönliches CrossChAPP-Konto.</p></div></section><?php endif; ?>
<main class="shell content auth-content">
<?php if ($authMode === 'register'): ?>
<section class="panel login-panel registration-panel"><h2>Neues Konto anlegen</h2><form id="register-form" novalidate>
<div class="auth-name-row"><label>Vorname *<input name="first_name" autocomplete="given-name" required></label><label>Nachname *<input name="last_name" autocomplete="family-name" required></label></div>
<label>E-Mail-Adresse *<input name="email" type="email" autocomplete="email" required aria-describedby="register-email-error"><span id="register-email-error" class="field-error" hidden>Bitte gib eine gültige E-Mail-Adresse ein.</span></label>
<fieldset class="home-chapter-picker"><legend>Heimatchapter <span>optional</span></legend><input id="home-chapter-id" name="home_chapter_org_id" type="hidden">
<div class="home-chapter-filters"><label>Land<select id="home-chapter-country"><option value="">Alle</option><option value="DE">Deutschland</option><option value="AT">Österreich</option></select></label><label>Suche<input id="home-chapter-search" type="search" placeholder="Name, Ort, PLZ oder Region"></label><label>Ort / PLZ<input id="home-chapter-location" type="search" placeholder="Ort oder PLZ"></label></div>
<button id="clear-home-chapter" type="button" class="secondary">Kein Heimatchapter auswählen</button><p id="selected-home-chapter">Kein Heimatchapter ausgewählt.</p><div id="home-chapter-results" class="home-chapter-results" role="radiogroup" aria-label="Heimatchapter auswählen"></div></fieldset>
<div class="auth-name-row"><label>Passwort *<input name="password" type="password" minlength="8" autocomplete="new-password" required aria-describedby="register-password-help register-password-error"><span id="register-password-help">Mindestens 8 Zeichen</span><span id="register-password-error" class="field-error" hidden>Das Passwort muss mindestens 8 Zeichen lang sein.</span></label><label>Passwort wiederholen *<input name="password_confirmation" type="password" minlength="8" autocomplete="new-password" required aria-describedby="register-confirmation-error"><span id="register-confirmation-error" class="field-error" hidden>Die Passwörter stimmen nicht überein.</span></label></div>
<div class="registration-actions"><button type="submit">Konto anlegen</button><button id="cancel-registration" type="button" class="secondary">Abbrechen</button></div></form><div id="register-message" class="message" role="alert" aria-live="polite"></div></section>
<?php elseif ($authMode === 'forgot'): ?>
<section class="panel login-panel"><h2>Passwort vergessen?</h2><form id="forgot-password-form"><label>E-Mail-Adresse<input name="email" type="email" autocomplete="email" required></label><button type="submit">Link zum Zurücksetzen senden</button></form><div id="forgot-message" class="message" role="status" aria-live="polite"></div><a href="/?view=login">Zur Anmeldung</a></section>
<?php elseif ($authMode === 'reset'): ?>
<section class="panel login-panel"><h2>Neues Passwort festlegen</h2><form id="reset-password-form" data-token="<?= htmlspecialchars($authToken, ENT_QUOTES, 'UTF-8') ?>"><label>Neues Passwort<input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Passwort wiederholen<input name="password_confirmation" type="password" minlength="8" autocomplete="new-password" required></label><button type="submit">Passwort speichern</button></form><div id="reset-message" class="message" role="alert" aria-live="polite"></div></section>
<?php elseif ($authMode === 'verified'): ?>
<?php $verificationMessages = ['verified' => 'E-Mail-Adresse erfolgreich bestätigt.', 'used' => 'Dieser Bestätigungslink wurde bereits verwendet.', 'expired' => 'Dieser Bestätigungslink ist abgelaufen.', 'already_verified' => 'Die E-Mail-Adresse wurde bereits bestätigt.', 'invalid' => 'Dieser Bestätigungslink ist ungültig.']; ?>
<section class="panel login-panel verification-panel"><p class="<?= $verificationResult === 'verified' ? 'verification-success' : 'verification-error' ?>"><?= htmlspecialchars($verificationMessages[$verificationResult] ?? $verificationMessages['invalid'], ENT_QUOTES, 'UTF-8') ?></p><a class="header-button" href="/?view=login">Anmelden</a></section>
<?php else: ?>
<section class="panel login-panel"><h2 id="login-heading">Anmelden</h2><form id="login-form"><label>E-Mail-Adresse oder Benutzername<input name="login" autocomplete="username" required></label><label>Passwort<input name="password" type="password" autocomplete="current-password" required></label><button type="submit">Anmelden</button></form><div id="login-message" class="message" role="alert" aria-live="polite"></div><div class="auth-links"><a href="/?view=forgot">Passwort vergessen?</a><a href="/?view=register">Neues Konto anlegen</a></div></section>
<?php endif; ?>
</main>
