<?php if (!in_array($authMode, ['verified'], true)): ?><section class="page-hero login-hero"><div class="shell"><p class="eyebrow">Benutzerkonto</p><h1><?= $authMode === 'register' ? 'Neues Konto anlegen' : ($authMode === 'forgot' ? 'Passwort zurücksetzen' : ($authMode === 'invite' ? 'Konto aktivieren' : 'Anmelden')) ?></h1><p>Verwalte dein persönliches CrossChAPP-Konto.</p></div></section><?php endif; ?>
<main class="shell content auth-content">
<?php if ($authMode === 'register'): ?>
<section class="panel login-panel registration-panel"><h2>Neues Konto anlegen</h2><form id="register-form" novalidate>
<div class="auth-name-row"><label>Vorname *<input name="first_name" autocomplete="given-name" required></label><label>Nachname *<input name="last_name" autocomplete="family-name" required></label></div>
<label>E-Mail-Adresse *<input name="email" type="email" autocomplete="email" required aria-describedby="register-email-error"><span id="register-email-error" class="field-error" hidden>Bitte gib eine gültige E-Mail-Adresse ein.</span></label>
<?php $chapterPicker = ['legend'=>'Heimatchapter','optional'=>true,'inputId'=>'home-chapter-id','inputName'=>'home_chapter_org_id','countryId'=>'home-chapter-country','searchId'=>'home-chapter-search','locationId'=>'home-chapter-location','clearId'=>'clear-home-chapter','clearLabel'=>'Kein Heimatchapter auswählen','selectedId'=>'selected-home-chapter','resultsId'=>'home-chapter-results','emptyLabel'=>'Kein Heimatchapter ausgewählt.','ariaLabel'=>'Heimatchapter auswählen']; require __DIR__ . '/partials/chapter-picker.php'; ?>
<div class="auth-name-row"><label>Passwort *<input name="password" type="password" minlength="8" autocomplete="new-password" required aria-describedby="register-password-help register-password-error"><span id="register-password-help">Mindestens 8 Zeichen</span><span id="register-password-error" class="field-error" hidden>Das Passwort muss mindestens 8 Zeichen lang sein.</span></label><label>Passwort wiederholen *<input name="password_confirmation" type="password" minlength="8" autocomplete="new-password" required aria-describedby="register-confirmation-error"><span id="register-confirmation-error" class="field-error" hidden>Die Passwörter stimmen nicht überein.</span></label></div>
<div id="skip-chapter-verification-option" class="skip-chapter-verification" hidden>
    <label><input name="skip_chapter_verification" type="checkbox" value="1" aria-describedby="skip-chapter-verification-tooltip"> <span>Chapter-Prüfung überspringen</span></label>
    <span class="field-tooltip"><button type="button" aria-label="Hinweis zur Chapter-Prüfung" aria-describedby="skip-chapter-verification-tooltip">i</button><span id="skip-chapter-verification-tooltip" role="tooltip">Es wird nicht geprüft, ob der Name in der Mitgliederliste des Chapters steht.</span></span>
</div>
<div class="registration-actions"><button type="submit">Konto anlegen</button><button id="cancel-registration" type="button" class="secondary">Abbrechen</button></div></form><div id="register-message" class="message" role="alert" aria-live="polite"></div></section>
<?php elseif ($authMode === 'forgot'): ?>
<section class="panel login-panel"><h2>Passwort vergessen?</h2><form id="forgot-password-form"><label>E-Mail-Adresse<input name="email" type="email" autocomplete="email" required></label><button type="submit">Link zum Zurücksetzen senden</button></form><div id="forgot-message" class="message" role="status" aria-live="polite"></div><a href="/?view=login">Zur Anmeldung</a></section>
<?php elseif ($authMode === 'reset'): ?>
<section class="panel login-panel"><h2>Neues Passwort vergeben</h2><form id="reset-password-form" data-token="<?= htmlspecialchars($authToken, ENT_QUOTES, 'UTF-8') ?>"><label>Neues Passwort<input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Neues Passwort wiederholen<input name="password_confirmation" type="password" minlength="8" autocomplete="new-password" required></label><button type="submit">Passwort speichern</button></form><div id="reset-message" class="message" role="alert" aria-live="polite"></div></section>
<?php elseif ($authMode === 'invite'): ?>
<?php $inviteMessages=['invalid'=>'Dieser Einladungslink ist ungültig.','expired'=>'Dieser Einladungslink ist abgelaufen.','used'=>'Diese Einladung wurde bereits verwendet.']; ?>
<section class="panel login-panel invitation-activation-panel"><h2>Konto aktivieren</h2>
<?php if (($invitationResult['status']??'invalid') === 'valid'): $inv=$invitationResult['invitation']; ?>
<dl class="invitation-account-data"><dt>Vorname</dt><dd><?=htmlspecialchars((string)$inv['firstName'],ENT_QUOTES,'UTF-8')?></dd><dt>Nachname</dt><dd><?=htmlspecialchars((string)$inv['lastName'],ENT_QUOTES,'UTF-8')?></dd><dt>E-Mail</dt><dd><?=htmlspecialchars((string)$inv['email'],ENT_QUOTES,'UTF-8')?></dd><dt>Chapter</dt><dd><?=htmlspecialchars((string)$inv['chapterName'],ENT_QUOTES,'UTF-8')?></dd></dl>
<form id="invitation-activation-form" data-token="<?=htmlspecialchars($invitationToken,ENT_QUOTES,'UTF-8')?>" novalidate><div class="auth-name-row"><label>Passwort<input name="password" type="password" minlength="8" autocomplete="new-password" required><span class="field-error" data-password-error hidden>Das Passwort muss mindestens 8 Zeichen lang sein.</span></label><label>Passwort wiederholen<input name="password_confirmation" type="password" minlength="8" autocomplete="new-password" required><span class="field-error" data-confirmation-error hidden>Die Passwörter stimmen nicht überein.</span></label></div><button type="submit">Konto aktivieren</button></form><div id="invitation-activation-message" class="message" role="alert"></div>
<?php else: ?><p class="verification-error"><?=htmlspecialchars($inviteMessages[$invitationResult['status']??'invalid']??$inviteMessages['invalid'],ENT_QUOTES,'UTF-8')?></p><?php endif; ?></section>
<?php elseif ($authMode === 'verified'): ?>
<?php $verificationMessages = ['verified' => 'E-Mail-Adresse erfolgreich bestätigt.', 'used' => 'Dieser Bestätigungslink wurde bereits verwendet.', 'expired' => 'Dieser Bestätigungslink ist abgelaufen.', 'already_verified' => 'Die E-Mail-Adresse wurde bereits bestätigt.', 'invalid' => 'Dieser Bestätigungslink ist ungültig.']; ?>
<section class="panel login-panel verification-panel"><p class="<?= $verificationResult === 'verified' ? 'verification-success' : 'verification-error' ?>"><?= htmlspecialchars($verificationMessages[$verificationResult] ?? $verificationMessages['invalid'], ENT_QUOTES, 'UTF-8') ?></p><a class="header-button" href="/?view=login">Anmelden</a></section>
<?php else: ?>
<section class="panel login-panel"><h2 id="login-heading">Anmelden</h2><form id="login-form"><input name="return_view" type="hidden" value="<?= htmlspecialchars($returnView, ENT_QUOTES, 'UTF-8') ?>"><input name="return_short_link" type="hidden" value="<?= htmlspecialchars($returnShortLink, ENT_QUOTES, 'UTF-8') ?>"><label>E-Mail-Adresse oder Benutzername<input name="login" autocomplete="username" required></label><label>Passwort<input name="password" type="password" autocomplete="current-password" required></label><button type="submit">Anmelden</button></form><div id="login-message" class="message" role="alert" aria-live="polite"></div><div class="auth-links"><a href="/?view=forgot">Passwort vergessen?</a><a href="/?view=register">Neues Konto anlegen</a></div></section>
<?php endif; ?>
</main>
