<?php
declare(strict_types=1);
foreach(['Auth','Database','JsonResponse','ClientIp','UserRepository','MailSettingsRepository','MailService','InvitationRepository','HomeChapterVerificationService','InvitationService','InvitationFactory']as$file)require_once dirname(__DIR__,2).'/src/'.$file.'.php';
$identity=Auth::requireUserManagementJson();$factory=InvitationFactory::create();
if($_SERVER['REQUEST_METHOD']==='GET'){$response=['invitations'=>$factory['repository']->open()];if(Auth::isFullAdmin())$response['template']=$factory['mailSettings']->templates()['user_invitation'];JsonResponse::send($response);}
Auth::requireCsrfJson();
try{$payload=json_decode(file_get_contents('php://input')?:'',true,32,JSON_THROW_ON_ERROR);if($_SERVER['REQUEST_METHOD']==='POST'){if(!is_array($payload))throw new JsonException('Ungültige Anfrage.');$fingerprint=hash('sha256',json_encode([trim((string)($payload['first_name']??'')),trim((string)($payload['last_name']??'')),strtolower(trim((string)($payload['email']??''))),(int)($payload['home_chapter_org_id']??0)],JSON_UNESCAPED_UNICODE));$override=(string)($payload['verification_override_token']??'');$pending=$_SESSION['invitation_verification_override']??null;$approved=is_array($pending)&&$override!==''&&(int)($pending['inviter_id']??0)===(int)$identity['user_id']&&hash_equals((string)($pending['token']??''),$override)&&hash_equals((string)($pending['fingerprint']??''),$fingerprint);if($override!==''&&!$approved)JsonResponse::send(['error'=>'Die manuelle Freigabe ist für diese Einladungsdaten nicht gültig.','code'=>'override_not_allowed'],409);$result=$factory['service']->invite($payload,(int)$identity['user_id'],$approved,ClientIp::address());unset($_SESSION['invitation_verification_override']);JsonResponse::send(['invited'=>true,'invitation'=>$result],201);}if(!Auth::isFullAdmin())JsonResponse::send(['error'=>'Admin-Berechtigung erforderlich.'],403);if($_SERVER['REQUEST_METHOD']==='PUT'){$factory['mailSettings']->saveTemplate('user_invitation',(string)($payload['subject']??''),(string)($payload['body']??''));JsonResponse::send(['saved'=>true]);}if($_SERVER['REQUEST_METHOD']==='DELETE'){$id=filter_var($payload['id']??null,FILTER_VALIDATE_INT);if($id===false||!$factory['repository']->cancel((int)$id))JsonResponse::send(['error'=>'Die Einladung wurde nicht gefunden.'],404);JsonResponse::send(['cancelled'=>true]);}JsonResponse::send(['error'=>'Methode nicht erlaubt.'],405);}
catch(HomeChapterVerificationException $e){$token=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$_SESSION['invitation_verification_override']=['token'=>$token,'fingerprint'=>$fingerprint??'','reason'=>$e->reason,'inviter_id'=>(int)$identity['user_id']];$message=match($e->reason){'chapter_member_not_found'=>'Der Name konnte im ausgewählten Chapter nicht gefunden werden.','ambiguous'=>'Der BNI-Eintrag konnte nicht eindeutig zugeordnet werden.',default=>'Die Chapter-Prüfung konnte derzeit nicht durchgeführt werden.'};JsonResponse::send(['error'=>$message,'message'=>$message,'code'=>$e->reason,'technicalReason'=>$e->technicalReason,'canOverride'=>true,'overrideToken'=>$token],$e->reason==='technical_unavailable'?503:422);}
catch(JsonException|InvalidArgumentException $e){JsonResponse::send(['error'=>$e->getMessage()],400);}catch(DomainException $e){JsonResponse::send(['error'=>$e->getMessage()],409);}catch(Throwable $e){JsonResponse::send(['error'=>$e->getMessage()==='Die Einladung konnte nicht versendet werden.'?$e->getMessage():'Die Einladung konnte nicht verarbeitet werden.'],500);}
